Repository SinsaStation/FullStackCodingBot, pull requests merged in 2021-07, with the labels that each got.

#24 [seok] MainVC & ItemVC
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ItemCell.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/XibView.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/SceneDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/CommonViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GiftViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, seok

#25 시점 뷰 세팅 + 유닛 애니메이션 일부 구현
  .DS_Store
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/ScreenSize.swift
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, song

#29 [team] Refactoring
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/cSharp.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/cSharp.imageset/cSharp.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/javaScript.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/javaScript.imageset/javaScript.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/php.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/php.imageset/php.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/python.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/python.imageset/python.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/ruby.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/ruby.imageset/ruby.jpeg
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/theC.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/logos/theC.imageset/theC.png
  FullStackCodingBot/FullStackCodingBot/Constant/UnitCount.swift
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Main/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
Labels: team

#30 회전, 투명도 애니메이션 추가
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/Pods/Pods.xcodeproj/project.pbxproj
Labels: team

#32 Game Scene 일부 구현
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/UnitCount.swift
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Main/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, song

#37 디버그 + Game Scene 간의 흐름 구현
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.xcworkspace/xcuserdata/song.xcuserdatad/UserInterfaceState.xcuserstate
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/UnitCount.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameOverButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/PauseButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Main/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinatorType.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
Labels: enhancement, refactoring, song

#52 [seok] Item View & Logic 수정
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/TransitionModel.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
Labels: seok

#54 [seok] ItemStorageType Unit Test 추가
  FullStackCodingBot/Full StackTests/Info.plist
  FullStackCodingBot/Full StackTests/StorageTest.swift
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot.xcodeproj/xcshareddata/xcschemes/FullStackCodingBot.xcscheme
  FullStackCodingBot/Podfile
  FullStackCodingBot/Podfile 2
  FullStackCodingBot/Podfile.lock
Labels: seok

#55 [seok] GameScene Logic Refactoring
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
Labels: seok

#56 [seok] wrongAction 화면 떨림 구현
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
Labels: seok

#57 [seok] 게임 난이도 조절, 구조 변경
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameOverButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/PauseButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ViewModelBindableType.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
Labels: seok

#59 [seok] 구글 애드몹 보상형 광고 추가
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/Podfile
  FullStackCodingBot/Podfile.lock
Labels: seok

#60 [seok] Refactoring code
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
Labels: refactoring, seok

#61 [seok] 7.20 ~ 7.21 작업내용정리
  FullStackCodingBot/Full StackTests/Info.plist
  FullStackCodingBot/Full StackTests/StorageTest.swift
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot.xcodeproj/xcshareddata/xcschemes/FullStackCodingBot.xcscheme
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameOverButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/PauseButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ViewModelBindableType.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/TransitionModel.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
  FullStackCodingBot/Podfile
  FullStackCodingBot/Podfile.lock
Labels: enhancement, refactoring, seok

#63 임시 앱아이콘 추가
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/1024.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/120-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/120.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/152.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/167.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/180.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/20.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/29.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/40-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/40-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/40.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/58-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/58.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/60.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/76.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/80-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/80.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/87.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/AppIcon.appiconset/Contents.json
  FullStackCodingBot/Podfile.lock
Labels: team

#70 [seok] Coredata 구현
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
Labels: enhancement, team

#72 Shop Scene - Ads & Reward
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot.xcodeproj/xcshareddata/xcschemes/FullStackCodingBot.xcscheme
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_box.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_box.imageset/background_box-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_box.imageset/background_box-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_box.imageset/background_box.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red.imageset/item_gift_red-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red.imageset/item_gift_red-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red.imageset/item_gift_red.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red_ad.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red_ad.imageset/item_gift_red_ad-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red_ad.imageset/item_gift_red_ad-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_red_ad.imageset/item_gift_red_ad.png
  FullStackCodingBot/FullStackCodingBot/Constant/Font.swift
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/AdStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ShopCell.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/AdViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: enhancement, song

#83 [seok] CoreData 기능구현
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/MemoryStorage/ItemStorageType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorageType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/AdViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/CommonViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/RankViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: enhancement, refactoring, seok

#87 Game Scene Details - Fever Mode / Refactoring
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever.png
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameStatus.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManagerType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/FeverTimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ReplicateAnimationView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
Labels: enhancement, song

#89 [team] BE/iOS 브랜치 병합
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_fever.imageset/text_fever.png
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameStatus.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManagerType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/FeverTimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ReplicateAnimationView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
Labels: team

#91 fix: 스토리지의 게임 유닛목록 동기화 문제
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
Labels: bug, team

#95 [seok] RankViewController LeaderBoard 구현
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/VersionErrorViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/RankViewModel.swift
Labels: enhancement, refactoring, seok

#96 [team] review를 위한 dev 병합 후 main 브랜치와 병합
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/VersionErrorViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/RankViewModel.swift
Labels: enhancement, team

#103 광고 업데이트 문제 해결
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: bug, song

#104 dev 브랜치 머지
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_plain.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_plain.imageset/button_plain-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_plain.imageset/button_plain-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_plain.imageset/button_plain.png
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorageType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: bug, enhancement, song

#107 [team] Game ReadyMode 구현 및 Apple Game Center Leader Board
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/VersionErrorViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/RankViewModel.swift
Labels: enhancement, refactoring, team

#113 [seok] Apple Game Center와 Firebase 로그인 연동
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud0.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud0.imageset/item_cloud 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud0.imageset/item_cloud-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud1.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud1.imageset/item_cloud2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud1.imageset/item_cloud2-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud1.imageset/item_cloud2-2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud2.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud2.imageset/item_cloud3 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud2.imageset/item_cloud3-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_cloud2.imageset/item_cloud3-2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_coffeeMachine.imageset/Contents 5.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_coffeeMachine.imageset/Contents 6.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor.imageset/item_computer_monitor 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor.imageset/item_computer_monitor-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor.imageset/item_computer_monitor-2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor_score.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/item_computer_monitor_score.imageset/item_computer_monitor_score 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_gameover.imageset/text_gameover_red-2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_paused.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_paused.imageset/text_paused_black 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_paused.imageset/text_paused_black-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_paused.imageset/text_paused_black-2 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_yourscore.imageset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_yourscore.imageset/text_yourscore 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_yourscore.imageset/text_yourscore-1 3.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/texts/text_yourscore.imageset/text_yourscore-2 3.png
  FullStackCodingBot/FullStackCodingBot/Model/NetworkDTO.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManager 3.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManagerType 3.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/FeverManagerType 4.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManagerType 3.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManagerType 3.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/TimeManagerType 4.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameButtonController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/GameOverButtonController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/PauseButtonController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/LoadingViewController 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/RankViewController 3.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/VersionErrorViewController 3.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ViewModelBindableType 3.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  README.md
Labels: enhancement, seok
