Repository SinsaStation/FullStackCodingBot, pull requests merged in 2021-09, with the labels that each got.

#187 [1.0.4] 버전 종합 패치
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup@3x.png
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/BackgroundAnimation.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/FadeInTextView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/TypeWriterView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/UnitInfo - keyColor.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/AverageColor.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/Color.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/Font.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/ScreenSize.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameOverDialogView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/MainItemView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/RewardPopupView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Reward/ShopCell.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: bug, refactoring, enhancement, team

#188 [1.0.4] 버전 종합 패치
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/energy_popup.imageset/energy_popup@3x.png
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/BackgroundAnimation.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/FadeInTextView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/Text Animation Views/TypeWriterView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Animation/UnitInfo - keyColor.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/AverageColor.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/Color.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/Font.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions & Contants/ScreenSize.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameOverDialogView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/MainItemView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Item/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/RewardPopupView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Reward/ShopCell.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: bug, refactoring

#193 [#190] Scene & SceneCoordinator 객체 리팩토링
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/AppCycle/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinatorType.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneType/AlertScene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneType/GameHelperScene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneType/GameScene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneType/MainScene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneType/SceneType.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/StoryViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: refactoring, seok
