Repository SinsaStation/FullStackCodingBot, pull requests merged in 2021-08, with the labels that each got.

#121 [seok] Setting Scene
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, seok

#122 [seok] Setting Scene 구현 및 폰트적용
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: enhancement, seok

#125 [seok] SettingInformation 생성
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/SettingInformation.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/SettingSwitchController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, seok

#126 [seok] merge 후 리뷰
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/SettingInformation.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/SettingSwitchController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/LoadingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: enhancement, seok

#127 Text Animation 최적화
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions/UIImageExtension.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/FeverTimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReplicateAnimationView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/ShopCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/SkyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/FadeInTextView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TypeWriterView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: enhancement, song

#128 feat: 유닛 이름 변경
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.swift
Labels: enhancement, team

#130 [seok] SettingScene UI
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Extensions/UIImageExtension.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/FeverTimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/GameBackgroundView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReplicateAnimationView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeBarView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/TimeProgressView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/UnitPerspectiveView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/ItemCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/ShopCell.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/SkyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/FadeInTextView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TypeWriterView.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile.lock
  README.md
Labels: enhancement, seok

#134 [seok] SettingScene UI 변경
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  README.md
Labels: enhancement, seok

#135 Sound/Vibration User Default 반영
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading.png
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameStatus.swift
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/BGM/MusicStation.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/Sound Effects /Game/GameSoundEffectStation.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/Sound Effects /Main/SingleSoundEffectStation.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: enhancement, song

#136 fix: 오토레이아웃, 폰트 개선
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting.png
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
Labels: enhancement, team

#137 [seok] StoryScene 추가
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_setting.imageset/button_setting.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/item_gift_loading.imageset/item_gift_loading.png
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/StoryManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/SyetemSettings.swift
  FullStackCodingBot/FullStackCodingBot/Model/GameStatus.swift
  FullStackCodingBot/FullStackCodingBot/Model/ShopItem.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/BGM/MusicStation.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/Sound Effects /Game/GameSoundEffectStation.swift
  FullStackCodingBot/FullStackCodingBot/Sounds/Sound Effects /Main/SingleSoundEffectStation.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/StoryViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/ItemViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/StoryViewModel.swift
Labels: enhancement, seok

#138 [seok] StoryScene
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Constant/StoryManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/StoryViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/StoryViewModel.swift
  README.md
Labels: enhancement, seok

#139 [seok] refactoring
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/StoryViewModel.swift
Labels: refactoring, seok

#142 Story Animations
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/intro.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/intro.imageset/intro.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/outro.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/outro.imageset/outro-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_bad.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_bad.imageset/story_akduk_bad.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_bad2.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_bad2.imageset/story_akduk_bad2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_normal.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_normal.imageset/story_akduk_normal.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_office1.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_office1.imageset/office1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_angry.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_angry.imageset/story_person_angry.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_bad.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_bad.imageset/story_person_bad.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_bad2.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_bad2.imageset/story_person_bad2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_normal.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_normal.imageset/story_person_normal.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_skip.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_skip.imageset/button_skip.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_story.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_story.imageset/button_story.png
  FullStackCodingBot/FullStackCodingBot/Constant/StoryManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/Line.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/Script.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/StoryManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/StoryViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Story/FullImageStoryView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Story/PersonStoryView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/StoryViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: enhancement, song

#143 [seok] Error 처리 방식 변경
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: refactoring, seok

#145 [team] Neo둥근모 폰트 스토리 적용
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile
  FullStackCodingBot/Podfile.lock
  FullStackCodingBot/neodgm.ttf
Labels: team, asset

#146 [team] Neo둥근모 폰트 스토리 적용
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
  FullStackCodingBot/Podfile
  FullStackCodingBot/Podfile.lock
  FullStackCodingBot/neodgm.ttf
Labels: team, asset

#147 [seok] HowToPlayVC
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12.png
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/HowToPlay/Manual.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/HowToPlayViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/HowToPlayViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: enhancement, seok

#148 [seok] Button 이동 구현 및 리팩터링
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/HowToPlayButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/HowToPlayViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/HowToPlayViewModel.swift
Labels: refactoring, enhancement, seok

#151 [seok] Error처리, HowToPlay
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.04.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.46.45.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.48.49.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.47.17.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12-1.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12-2.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Simulator Screen Shot - iPhone 12 - 2021-08-10 at 15.52.12.png
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/HowToPlay/Manual.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/ErrorManager/ErrorManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/HowToPlayButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/Button/MainButtonController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/HowToPlayViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/TransitionModel.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/HowToPlayViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/ShopViewModel.swift
Labels: refactoring, enhancement, seok

#156 [seok] Error Handling
  FullStackCodingBot/FullStackCodingBot/Service/ErrorManager/ErrorManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: refactoring, seok

#160 에셋 변경 & 게임오버 스토리 & 매치 시 코드 보여주기
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_happy.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_happy.imageset/story_akduk_happy.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_happy.imageset/story_akduk_happy@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_happy.imageset/story_akduk_happy@3x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_love.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_love.imageset/story_akduk_love.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_love.imageset/story_akduk_love@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_akduk_love.imageset/story_akduk_love@3x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_happy.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_happy.imageset/story_person_happy.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_happy.imageset/story_person_happy@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/Story/story_person_happy.imageset/story_person_happy@3x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/launch.imageset/launch.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/launch.imageset/launch@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/launch.imageset/launch@3x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/darkblue.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/darkgreen.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/darkgreen.colorset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/darkgreen.colorset/Contents 4.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/digitalgreen.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/lightbrown.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/mildgreen.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/mildgreen.colorset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/mildgreen.colorset/Contents 4.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/red.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/yellow.colorset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/yellow.colorset/Contents 3.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/yellow.colorset/Contents 4.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/keyboard.imageset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/keyboard.imageset/keyboard.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/keyboard.imageset/keyboard@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/items/keyboard.imageset/keyboard@3x.png
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Model/Story/GameStoryManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/Line.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/Script.swift
  FullStackCodingBot/FullStackCodingBot/Model/Story/StoryManager.swift
  FullStackCodingBot/FullStackCodingBot/Model/Unit.swift
  FullStackCodingBot/FullStackCodingBot/Model/UnitInfo.swift
  FullStackCodingBot/FullStackCodingBot/Service/GameManager/GameUnitManager.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/SkyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/FadeInTextView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TypeWriterView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/LaunchScreen.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  README.md
Labels: enhancement, song, asset

#161 리워드 로드 버그 수정 + 배너 광고 추가
  FullStackCodingBot/FullStackCodingBot/Constant/IdentifierManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/AdStorage.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
Labels: bug, enhancement, song

#162 기기 사이즈에 따라 폰트 사이즈 유동적으로 조정
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_stack_index.imageset/background_stack_index.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_stack_index.imageset/background_stack_index@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/backgrounds/background_stack_index.imageset/background_stack_index@3x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_start.imageset/button_start.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_start.imageset/button_start@2x.png
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/buttons/button_start.imageset/button_start@3x.png
  FullStackCodingBot/FullStackCodingBot/Constant/Font.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/HowToPlayViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ItemViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/DialogView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/MainItemView.xib
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/Text Animation Views/TextPresentView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Story/FullImageStoryView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Story/PersonStoryView.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
Labels: enhancement, song, asset

#163 트랜지션 조정 + 세팅 터치 제스처 추가
  FullStackCodingBot/FullStackCodingBot/Constant/ScreenSize.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameOverViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/GameViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Game/PauseViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/MainViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/SettingViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReadyView.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Game/ReplicateAnimationView.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/TransitionModel.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameOverViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/GameViewModel.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/PauseViewModel.swift
Labels: enhancement, song

#168 [seok] Xcode Warning해결
  FullStackCodingBot/Full StackTests/AdStorageTest.swift
  FullStackCodingBot/Full StackTests/MockAdStorage.swift
  FullStackCodingBot/Full StackTests/StorageTest.swift
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: refactoring, seok

#169 [seok] Error 로깅, Xcode Warning
  FullStackCodingBot/Full StackTests/AdStorageTest.swift
  FullStackCodingBot/Full StackTests/MockAdStorage.swift
  FullStackCodingBot/Full StackTests/StorageTest.swift
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameFever.imageset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameMain.imageset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GameOver.imageset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/GamePause.imageset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/HowToPlay/Item.imageset/Contents 2.json
  FullStackCodingBot/FullStackCodingBot/Constant/Extension.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/ErrorManager/ErrorManager 2.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/Scene.swift
  FullStackCodingBot/FullStackCodingBot/View/Scene/SceneCoordinator.swift
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: refactoring, seok

#174 [seok] 배포 리젝 핫픽스
  FullStackCodingBot/Full Stack.entitlements
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  README.md
Labels: refactoring, enhancement, seok

#175 오프라인 플레이 지원
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: enhancement, team

#176 [team] OffLine & OnLine Data 저장 및 불러오기 연동
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Constant/AlertMessage.swift
  FullStackCodingBot/FullStackCodingBot/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  FullStackCodingBot/FullStackCodingBot/Model/DTO/NetworkDTO.swift
  FullStackCodingBot/FullStackCodingBot/Service/DataFormatManager/DataFormatManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Controller/ViewController/Main/ShopViewController.swift
  FullStackCodingBot/FullStackCodingBot/View/Delegate/AppDelegate.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: refactoring, team, song, seok

#179 다크모드 반영
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey1.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey2.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey3.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
Labels: bug, song, asset

#181 중복 유닛 생성 문제 해결
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: bug, team

#182 [1.0.3] firebase uuid 버그 & 다크모드 대응
  FullStackCodingBot/FullStackCodingBot.xcodeproj/project.pbxproj
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey1.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey2.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Assets.xcassets/colors/grey3.colorset/Contents.json
  FullStackCodingBot/FullStackCodingBot/Info.plist
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManager.swift
  FullStackCodingBot/FullStackCodingBot/Service/FirebaseStorage/DatabaseManagerType.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorage.swift
  FullStackCodingBot/FullStackCodingBot/Service/PersistenceStorage/PersistenceStorageType.swift
  FullStackCodingBot/FullStackCodingBot/View/CustomView/Main/LevelUpButton.xib
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Base.lproj/Main.storyboard
  FullStackCodingBot/FullStackCodingBot/View/Storyboard/Game.storyboard
  FullStackCodingBot/FullStackCodingBot/ViewModel/MainViewModel.swift
  FullStackCodingBot/Podfile.lock
Labels: bug, team
